### ISSUE TITLE
IPV6 SDN

### ISSUE THREAD

**Issue by spazwik** [vishalsingh9535/SDN-DDOS-Detection-and-Mitigation-#1]
Hi,

I will like to know if this your project can be further improved to work with IPV6 instead of IPV4.

**Comment by vishalsingh45** [comment]
Yes you can try doing it, you will have to modify the network simulator and network data flow parameters.

**Comment by spazwik** [comment]
I modified the Controller Srckey to IPV6 but didn't work, after addressing the network in IPv6 also

**Comment by vishalsingh45** [comment]
Sorry bro, Never heard of the controller srckey.

**Comment by spazwik** [comment]
Ok thanks.
